# Generated by Django 5.1.1 on 2025-04-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='username',
            field=models.CharField(default='empty', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
