# Generated by Django 5.1.1 on 2025-04-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0007_alter_role_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='author',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Admin'), ('normal_user', 'Normal User')], max_length=20),
        ),
    ]
