# Generated by Django 5.1.1 on 2025-05-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0013_listing_is_deleted_alter_role_role_name_inbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Admin'), ('normal_user', 'Normal User')], max_length=20),
        ),
    ]
