# Generated by Django 5.2 on 2025-05-11 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0017_alter_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petadoption',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='potty_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('cancelled', 'Cancelled')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='petadoption',
            table=None,
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('id_document', models.ImageField(upload_to='id_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thriftapp.webuser')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thriftapp.petadoption')),
            ],
        ),
    ]
